// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhIle_mp7oLTbtw6-zZH2pbVrmoY5OS3c',
    appId: '1:822670410343:web:14774056168e1538dd8ac2',
    messagingSenderId: '822670410343',
    projectId: 'instagram-tut-42471',
    authDomain: 'instagram-tut-42471.firebaseapp.com',
    storageBucket: 'instagram-tut-42471.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKild3gLCo7g1dVXkvkU0kmipdv7l1xjg',
    appId: '1:822670410343:android:82317c3085ea6b68dd8ac2',
    messagingSenderId: '822670410343',
    projectId: 'instagram-tut-42471',
    storageBucket: 'instagram-tut-42471.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFNwbazW6cH6BR71N7Zu9rRE8x_aKxR3Y',
    appId: '1:822670410343:ios:c3d730c839b44240dd8ac2',
    messagingSenderId: '822670410343',
    projectId: 'instagram-tut-42471',
    storageBucket: 'instagram-tut-42471.appspot.com',
    iosBundleId: 'com.example.instagramFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDFNwbazW6cH6BR71N7Zu9rRE8x_aKxR3Y',
    appId: '1:822670410343:ios:c976b3fca1b6bca0dd8ac2',
    messagingSenderId: '822670410343',
    projectId: 'instagram-tut-42471',
    storageBucket: 'instagram-tut-42471.appspot.com',
    iosBundleId: 'com.example.instagramFlutter.RunnerTests',
  );
}
